"""Render audit/results.json as docs/AUDIT_2026-09.md (M9 Task 4).

The verdict table is generated, never hand-written. A published table someone edits by
hand is the same artefact the first audit was written about: a document asserting an
outcome, drifting away from the thing it describes.

    python scripts/audit_claims.py && python scripts/publish_verdict_table.py
"""

from __future__ import annotations

import json
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
RESULTS = PROJECT_ROOT / "audit" / "results.json"
OUTPUT = PROJECT_ROOT / "docs" / "AUDIT_2026-09.md"

ORDER = ["CONTRADICTED", "SUPERSEDED", "CAVEAT", "CONFIRMED", "NOT_CLAIMED",
         "UNVERIFIABLE", "ERROR"]

BASELINE = {"CONFIRMED": 78, "CAVEAT": 18, "CONTRADICTED": 11, "UNVERIFIABLE": 3}

NOTE = {
    "CONTRADICTED": "the check ran and the claim is false",
    "SUPERSEDED": "true at the first audit, false now because the gap was closed",
    "CAVEAT": "holds, with a limitation stated in the README",
    "CONFIRMED": "the check ran and the claim holds",
    "NOT_CLAIMED": "the current documentation does not assert it, with a reason",
    "UNVERIFIABLE": "no command settles it",
}


def escape(text: str) -> str:
    return str(text).replace("|", "\|").replace("\n", " ")


def main() -> None:
    data = json.loads(RESULTS.read_text(encoding="utf-8"))
    rows = data["results"]
    counts = {v: sum(1 for r in rows if r["verdict"] == v) for v in ORDER}

    lines = [
        "# Claim audit — 2026-09",
        "",
        "**Generated by `scripts/publish_verdict_table.py` from `audit/results.json`.**",
        "Do not edit by hand. Regenerate with:",
        "",
        "```bash",
        "python scripts/audit_claims.py && python scripts/publish_verdict_table.py",
        "```",
        "",
        f"Re-run of the {data['baseline_audit']['date']} audit "
        f"(`{data['baseline_audit']['source']}`, commit "
        f"`{data['baseline_audit']['commit']}`) against the finished system, plus the "
        f"claims the rebuilt README makes.",
        "",
        f"Generated {data['generated_at']}. **{len(rows)} claims.**",
        "",
        "## Totals",
        "",
        "| Verdict | 2026-08-20 | now | |",
        "|---|---:|---:|---|",
    ]

    for verdict in ORDER:
        if not counts[verdict] and verdict not in BASELINE:
            continue

        before = BASELINE.get(verdict)
        lines.append(
            f"| {'**' + verdict + '**' if verdict == 'CONTRADICTED' else verdict} "
            f"| {before if before is not None else '—'} "
            f"| {'**' + str(counts[verdict]) + '**' if verdict == 'CONTRADICTED' else counts[verdict]} "
            f"| {NOTE.get(verdict, '')} |"
        )

    coverage = data["coverage"]
    lines += [
        "",
        f"**Coverage.** {coverage['executable']} claims have an executable check, "
        f"{coverage['manual_judged']} are manual judgements, and "
        f"{coverage['inherited_unchecked']} are inherited from the first audit with no "
        f"new check written. The last group is flagged `inherited: true` in "
        f"`audit/claims.json` so this figure cannot be inflated by silence.",
        "",
        "## The eleven claims the rebuild was commissioned to fix",
        "",
        "| # | Claim | 2026-08-20 | now | Evidence |",
        "|---|---|---|---|---|",
    ]

    for row in rows:
        if row["baseline_verdict"] != "CONTRADICTED":
            continue

        lines.append(
            f"| {row['id']} | {escape(row['claim'])[:90]} | CONTRADICTED "
            f"| **{row['verdict']}** | {escape(row['evidence'])[:150]} |"
        )

    superseded = [r for r in rows if r["verdict"] == "SUPERSEDED"]

    if superseded:
        lines += [
            "",
            "## Superseded — true then, false now because it was fixed",
            "",
            "These were honest limitations in August. The milestones built them, so "
            "repeating them today would be a new false claim. The README is checked "
            "against this list.",
            "",
            "| # | Claim | Closed by |",
            "|---|---|---|",
        ]
        lines += [
            f"| {r['id']} | {escape(r['claim'])[:80]} | {escape(r['evidence'])[:90]} |"
            for r in superseded
        ]

    lines += ["", "## Every claim", "",
              "| # | Claim | Before | Now | Evidence |", "|---|---|---|---|---|"]

    for row in sorted(rows, key=lambda r: r["id"]):
        changed = "" if row["verdict"] == row["baseline_verdict"] else " ←"
        lines.append(
            f"| {row['id']} | {escape(row['claim'])[:88]} | {row['baseline_verdict']} "
            f"| {row['verdict']}{changed} | {escape(row['evidence'])[:130]} |"
        )

    OUTPUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"{len(rows)} claims -> {OUTPUT}")
    print("  " + "  ".join(f"{v}={counts[v]}" for v in ORDER if counts[v]))


if __name__ == "__main__":
    main()
